apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awesome-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  volumeName: awesome-pv
  resources:
    requests:
      storage: 8Gi
  storageClassName: aws-efs